default: &default
  adapter: postgresql
  user: kamesh
  password: codebrahma123
  hostname: localhost
  database: hiring

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
